"""add favorite column to trips

Revision ID: 089109849066
Revises: ca08496ac210
Create Date: 2023-08-16 13:21:57.985659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089109849066'
down_revision = 'ca08496ac210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
