"""empty message

Revision ID: 11b6f2cc8bc4
Revises: 050e0de4fdf9
Create Date: 2023-08-28 09:55:53.989600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b6f2cc8bc4'
down_revision = '050e0de4fdf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ingredients', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_books_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_book',
    sa.Column('recipe.id', sa.Integer(), nullable=False),
    sa.Column('book.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book.id'], ['books.id'], name=op.f('fk_recipe_book_book.id_books')),
    sa.ForeignKeyConstraint(['recipe.id'], ['recipes.id'], name=op.f('fk_recipe_book_recipe.id_recipes')),
    sa.PrimaryKeyConstraint('recipe.id', 'book.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_book')
    op.drop_table('books')
    op.drop_table('users')
    op.drop_table('recipes')
    # ### end Alembic commands ###
