"""empty message

Revision ID: 574c328044d1
Revises: 5e9a44f37a31
Create Date: 2023-10-17 14:54:24.076042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574c328044d1'
down_revision = '5e9a44f37a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
