"""adding user, book, and recipe tables

Revision ID: 63fbd3f8a6a4
Revises: 98a688828457
Create Date: 2023-08-25 13:48:38.990413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fbd3f8a6a4'
down_revision = '98a688828457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_books_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_book_association',
    sa.Column('recipe.id', sa.Integer(), nullable=False),
    sa.Column('book.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book.id'], ['books.id'], name=op.f('fk_recipe_book_association_book.id_books')),
    sa.ForeignKeyConstraint(['recipe.id'], ['recipes.id'], name=op.f('fk_recipe_book_association_recipe.id_recipes')),
    sa.PrimaryKeyConstraint('recipe.id', 'book.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_book_association')
    op.drop_table('books')
    op.drop_table('users')
    op.drop_table('recipes')
    # ### end Alembic commands ###
