""" adding hours worked column to timelog table

Revision ID: 71a15993b0e0
Revises: b30a88e7e6b6
Create Date: 2024-04-16 16:46:52.577159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a15993b0e0'
down_revision = 'b30a88e7e6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_worked', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.drop_column('hours_worked')

    # ### end Alembic commands ###
