"""removing Book and Recipe tables temporarily

Revision ID: 746d66cf795e
Revises: bffb21c625cd
Create Date: 2023-08-26 12:02:50.570008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746d66cf795e'
down_revision = 'bffb21c625cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('recipe_book_association')
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_books_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_book_association',
    sa.Column('recipe.id', sa.INTEGER(), nullable=False),
    sa.Column('book.id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book.id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['recipe.id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe.id', 'book.id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
