"""empty message

Revision ID: 76372e8c5e8e
Revises: 0ab118eefccd
Create Date: 2023-11-06 09:28:42.021989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76372e8c5e8e'
down_revision = '0ab118eefccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_column('current_value')

    # ### end Alembic commands ###
