"""empty message

Revision ID: 7ed78bbf0e74
Revises: 27d6078b207d
Create Date: 2023-10-31 07:27:09.129878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed78bbf0e74'
down_revision = '27d6078b207d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=True))
        batch_op.drop_column('quantity')
        batch_op.drop_column('purchase_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_value', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('value')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('purchase_value')

    # ### end Alembic commands ###
