"""empty message

Revision ID: 968e186c91fd
Revises: 
Create Date: 2023-10-28 18:31:48.159058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968e186c91fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothingitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('closets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clothingitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clothingitem_id'], ['clothingitems.id'], name=op.f('fk_closets_clothingitem_id_clothingitems')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_closets_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('closets')
    op.drop_table('users')
    op.drop_table('clothingitems')
    # ### end Alembic commands ###
