"""empty message

Revision ID: aa06161f2bc6
Revises: 
Create Date: 2023-10-16 12:58:33.278738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa06161f2bc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adoptions')
    op.drop_table('users')
    op.drop_table('pets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(), nullable=True),
    sa.Column('lname', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adoptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('pet_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='fk_adoptions_pet_id_pets'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_adoptions_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
