"""fixing recipe_book table name

Revision ID: aeed4643aecd
Revises: fcfea8defbe4
Create Date: 2023-08-26 12:14:39.089525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeed4643aecd'
down_revision = 'fcfea8defbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_book',
    sa.Column('recipe.id', sa.Integer(), nullable=False),
    sa.Column('book.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book.id'], ['books.id'], name=op.f('fk_recipe_book_book.id_books')),
    sa.ForeignKeyConstraint(['recipe.id'], ['recipes.id'], name=op.f('fk_recipe_book_recipe.id_recipes')),
    sa.PrimaryKeyConstraint('recipe.id', 'book.id')
    )
    op.drop_table('recipe_book_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_book_association',
    sa.Column('recipe.id', sa.INTEGER(), nullable=False),
    sa.Column('book.id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book.id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['recipe.id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe.id', 'book.id')
    )
    op.drop_table('recipe_book')
    # ### end Alembic commands ###
