"""update models setup

Revision ID: bae96cd7f7d4
Revises: 520a68251a56
Create Date: 2023-12-05 15:22:21.934834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae96cd7f7d4'
down_revision = '520a68251a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('user_connections')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_posts_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_connections',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user1', sa.INTEGER(), nullable=True),
    sa.Column('user2', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'pending'"), nullable=True),
    sa.ForeignKeyConstraint(['user1'], ['users.userID'], ),
    sa.ForeignKeyConstraint(['user2'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_comments_post_id_posts'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_comments_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
