"""added user id as fk in recipe

Revision ID: d0943b12aeb0
Revises: 8a300c2aa042
Create Date: 2023-08-25 17:25:20.483160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0943b12aeb0'
down_revision = '8a300c2aa042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
