"""added exercies id

Revision ID: e6f820950d3b
Revises: 44b9b04e2b97
Create Date: 2023-11-27 16:14:09.299727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f820950d3b'
down_revision = '44b9b04e2b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(), nullable=True),
    sa.Column('exercise', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_assignments_exercise_id_exercises'), 'exercises', ['exercise_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assignments_exercise_id_exercises'), type_='foreignkey')
        batch_op.drop_column('exercise_id')

    op.create_table('exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_type', sa.VARCHAR(), nullable=True),
    sa.Column('exercise', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercises')
    # ### end Alembic commands ###
