"""changine time punch model type

Revision ID: f3212e53e563
Revises: 71a15993b0e0
Create Date: 2024-04-16 17:28:28.090530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3212e53e563'
down_revision = '71a15993b0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.alter_column('clock_in',
               existing_type=sa.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('clock_out',
               existing_type=sa.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.alter_column('clock_out',
               existing_type=sa.Time(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('clock_in',
               existing_type=sa.Time(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
