"""adding recipes table back in

Revision ID: fcfea8defbe4
Revises: 276f861cc632
Create Date: 2023-08-26 12:10:41.807509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfea8defbe4'
down_revision = '276f861cc632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_book_association',
    sa.Column('recipe.id', sa.Integer(), nullable=False),
    sa.Column('book.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book.id'], ['books.id'], name=op.f('fk_recipe_book_association_book.id_books')),
    sa.ForeignKeyConstraint(['recipe.id'], ['recipes.id'], name=op.f('fk_recipe_book_association_recipe.id_recipes')),
    sa.PrimaryKeyConstraint('recipe.id', 'book.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_book_association')
    op.drop_table('recipes')
    # ### end Alembic commands ###
